"""Preserve legacy campaign data and verify a coherent versioned release.
Run against npm run preview; requires Python Playwright and Chromium.
"""
import json
import os
from pathlib import Path
from urllib.parse import urlparse, parse_qs
from playwright.sync_api import sync_playwright
URL=os.environ.get('TEST_URL','http://localhost:4173')
OUT=Path('artifacts');OUT.mkdir(exist_ok=True)
RELEASE='2026.10.03-2'
errors=[]
results=[]
# Values generated by the 92fd685 campaign implementation, before the finale existed.
legacy=[{'version':1,'stage':4,'wins':5,'losses':0,'draws':0,'clears':1,'completed':True},
        {'version':1,'stage':4,'wins':10,'losses':2,'draws':2,'clears':2,'completed':True},
        {'version':1,'stage':4,'wins':25,'losses':14,'draws':10,'clears':5,'completed':True}]
with sync_playwright() as p:
    browser=p.chromium.launch(executable_path=os.environ.get('CHROMIUM_PATH','/usr/bin/chromium'),args=['--no-sandbox'])
    for saved in legacy:
        page=browser.new_page(viewport={'width':320,'height':568},is_mobile=True,has_touch=True)
        page.on('pageerror',lambda e:errors.append(str(e)))
        page.add_init_script("if(!localStorage.getItem('last-trump-campaign'))localStorage.setItem('last-trump-campaign',"+json.dumps(json.dumps(saved))+");")
        stale=[];assets=[]
        def inspect(route):
            u=urlparse(route.request.url)
            if u.path.endswith(('/src/app.js','/src/game.js','/src/style.css')):
                assets.append(u.path)
                if parse_qs(u.query).get('v')!=[RELEASE]:
                    stale.append(route.request.url)
                    route.fulfill(body='throw new Error("stale unversioned asset");',content_type='text/javascript')
                    return
            route.continue_()
        page.route('**/*',inspect)
        page.goto(URL+'/?v='+RELEASE if not URL.endswith('/') else URL+'?v='+RELEASE)
        for attempt in range(3):
            assert page.locator('#completion').is_visible()
            assert 'celebrate' not in page.locator('#completion').get_attribute('class')
            assert not page.locator('#rules').evaluate('(e)=>e.open')
            assert page.evaluate('JSON.parse(localStorage.getItem("last-trump-campaign"))')==saved
            assert f'金メダル × {saved["clears"]}'==page.locator('#completion-count').inner_text()
            assert 'HTML・JS・CSS一致' in page.locator('#build-version').inner_text()
            if attempt<2:page.reload()
        assert not stale
        assert set(assets)=={'/src/app.js','/src/game.js','/src/style.css'}
        page.locator('#help').tap()
        assert page.locator('#build-version').is_visible()
        page.screenshot(path=str(OUT/f'release-legacy-{saved["clears"]}.png'))
        results.append({'legacy_clears':saved['clears'],'reloads':2,'checks':'all assets versioned; saved data unchanged; finale visible without replay'})
        page.close()

    for reduced in [False,True]:
        page=browser.new_page(viewport={'width':375,'height':548},is_mobile=True,has_touch=True,reduced_motion='reduce' if reduced else 'no-preference')
        page.on('pageerror',lambda e:errors.append(str(e)))
        page.add_init_script("Math.random=()=>0;if(!localStorage.getItem('last-trump-campaign'))localStorage.setItem('last-trump-campaign',JSON.stringify({version:1,stage:4,wins:4,losses:1,draws:2,clears:0,completed:false}));")
        page.goto(URL);page.locator('#ready').tap()
        for i,c in enumerate([2,3,4,5]):
            page.locator(f'[data-card="{c}"]').tap();page.locator('#action').tap()
            page.wait_for_function('!document.querySelector("#action").disabled')
            page.locator('#action').evaluate('(e)=>{for(let i=0;i<12;i++)e.click()}')
        page.wait_for_selector('#completion:not([hidden])')
        assert not page.locator('#arena').is_visible(), 'ordinary YOU WIN result must be replaced'
        assert page.locator('#completion-title').inner_text()=='五人制覇'
        assert page.locator('#completion').get_attribute('class')=='completion celebrate'
        assert page.locator('.completion-crown').evaluate('(e)=>getComputedStyle(e).animationName')==('none' if reduced else 'crown-arrives')
        assert page.evaluate('scrollY===0 && document.documentElement.scrollHeight<=innerHeight')
        saved=page.evaluate('JSON.parse(localStorage.getItem("last-trump-campaign"))')
        assert saved['version']==2 and saved['stage']==4 and saved['wins']==5 and saved['losses']==1 and saved['draws']==2 and saved['clears']==1 and saved['completed']
        assert saved['medals']=={'gold':1,'silver':0,'bronze':0}
        for _ in range(2):page.reload();assert page.locator('#completion').is_visible()
        assert page.evaluate('JSON.parse(localStorage.getItem("last-trump-campaign"))')==saved
        results.append({'fresh_champion':True,'reduced_motion':reduced,'checks':'ordinary result hidden; finale entered once; two reloads preserve completion and all scores'})
        page.close()
    browser.close()
assert not errors,errors
(OUT/'release-results.json').write_text(json.dumps({'results':results,'page_errors':errors},indent=2))
print(json.dumps({'results':results,'page_errors':errors},indent=2))
